sonar.projectKey=HanielCota_Cotani
sonar.organization=hanielcota
sonar.projectName=Cotani
sonar.sourceEncoding=UTF-8

# Source and Test directories
sonar.sources=cotani-cache/src/main,cotani-config/src/main,cotani-cooldown/src/main,cotani-core/src/main,cotani-economy/src/main,cotani-event/src/main,cotani-item/src/main,cotani-storage/src/main,cotani-task/src/main,cotani-teleport/src/main,cotani-text/src/main,cotani-user/src/main
sonar.tests=cotani-cache/src/test,cotani-config/src/test,cotani-cooldown/src/test,cotani-core/src/test,cotani-economy/src/test,cotani-event/src/test,cotani-item/src/test,cotani-storage/src/test,cotani-task/src/test,cotani-teleport/src/test,cotani-text/src/test,cotani-user/src/test

# Binary outputs for bytecode analysis
sonar.java.binaries=**/build/classes/java/main
sonar.java.test.binaries=**/build/classes/java/test

# Exclusions
sonar.exclusions=**/build/**, **/.gradle/**
