description = "Cotani — dependency alignment platform"

dependencies {
    constraints {
        api(project(":audit"))
        api(project(":audit-storage"))
        api(project(":cache"))
        api(project(":command"))
        api(project(":config"))
        api(project(":cooldown"))
        api(project(":core"))
        api(project(":dialog"))
        api(project(":display"))
        api(project(":economy"))
        api(project(":event"))
        api(project(":gui"))
        api(project(":hud"))
        api(project(":inventory"))
        api(project(":locale"))
        api(project(":item"))
        api(project(":metrics"))
        api(project(":nametag"))
        api(project(":npc"))
        api(project(":placeholder"))
        api(project(":permission"))
        api(project(":party"))
        api(project(":friend"))
        api(project(":queue"))
        api(project(":trade"))
        api(project(":punishment"))
        api(project(":location"))
        api(project(":mail"))
        api(project(":reward"))
        api(project(":reward-integration"))
        api(project(":redis"))
        api(project(":region"))
        api(project(":storage"))
        api(project(":task"))
        api(project(":teleport"))
        api(project(":text"))
        api(project(":user"))
    }
}
